In [2]:
import pandas as pd
import os
import ipwhois
from tqdm import tqdm
import IPy
from sklearn.model_selection import train_test_split
import xgboost
from sklearn import metrics
from sklearn.utils import class_weight
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import time
import datetime

In [3]:
PATH = r'D:\Documents\ITC\Workshops\Checkpoint\hackathon\cphackathon\Data'
file = 'EnrichedData.csv'

df = pd.read_csv(os.path.join(PATH, file))
df.head()

,Unnamed: 0,client,dst_ip,dst_port,epoch_time,label,protocol,received_bytes,sent_bytes,src_ip,type_dst,subtype_dst,type_src,subtype_src,log_sent_bytes,log_received_bytes
0,0,2,222.58.210.46,443,1547242292,benign,1,44096,67712,10.197.88.33,Internal,Class A,Internal,Class A,11,10
1,1,5,110.244.46.16,443,1547468725,benign,1,7712,1990,10.0.11.69,Internal,Class A,Internal,Class A,7,8
2,2,2,23.130.21.5,443,1547415821,benign,1,12928,8464,192.168.174.137,Internal,Class C,Internal,Class C,9,9
3,3,2,71.55.163.78,443,1547152973,benign,1,19808,4376,192.168.190.183,Internal,Class C,Internal,Class C,8,9
4,4,5,230.0.0.1,-1,1547070189,benign,1,0,252,10.0.11.2,Internal,Class A,Internal,Class A,5,0

In [4]:
df['real time']=df['epoch_time'].apply(lambda x: datetime.datetime.utcfromtimestamp(int(x)))

# column year, month, day

df['year'] = df['real time'].apply(lambda x: x.year)
df['month'] = df['real time'].apply(lambda x: x.month)
df['day'] = df['real time'].apply(lambda x: x.day)

In [5]:
df.head()

,Unnamed: 0,client,dst_ip,dst_port,epoch_time,label,protocol,received_bytes,sent_bytes,src_ip,type_dst,subtype_dst,type_src,subtype_src,log_sent_bytes,log_received_bytes,real time,year,month,day
0,0,2,222.58.210.46,443,1547242292,benign,1,44096,67712,10.197.88.33,Internal,Class A,Internal,Class A,11,10,2019-01-11 21:31:32,2019,1,11
1,1,5,110.244.46.16,443,1547468725,benign,1,7712,1990,10.0.11.69,Internal,Class A,Internal,Class A,7,8,2019-01-14 12:25:25,2019,1,14
2,2,2,23.130.21.5,443,1547415821,benign,1,12928,8464,192.168.174.137,Internal,Class C,Internal,Class C,9,9,2019-01-13 21:43:41,2019,1,13
3,3,2,71.55.163.78,443,1547152973,benign,1,19808,4376,192.168.190.183,Internal,Class C,Internal,Class C,8,9,2019-01-10 20:42:53,2019,1,10
4,4,5,230.0.0.1,-1,1547070189,benign,1,0,252,10.0.11.2,Internal,Class A,Internal,Class A,5,0,2019-01-09 21:43:09,2019,1,9

In [6]:
df.to_csv(r'D:\Documents\ITC\Workshops\Checkpoint\hackathon\cphackathon\Data\ErichData_with_time.csv')